--- #YAML:1.0
name:                CSS-Squish
version:             0.06
abstract:            Compact many CSS files into one big file
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    File::Spec:                    0
    Scalar::Util:                  0
    Test::LongString:              0
    URI:                           0
    URI::file:                     0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Thomas Sibley <trs@bestpractical.com>
